Repository git-hubsalt/omoib-frontend, pull requests merged in 2024-11, with the labels that each got.

#77 feat: 옷 정보 타입 생성 및 업로더에 추가
  src/components/Uploader/Uploader.tsx
  src/pages/Onboarding/index.tsx
  src/pages/OutfitRecommendations/index.tsx
  src/stores/clothesSelectorStore.ts
  src/types/type.ts
Labels: enhancement

#80 feat: 업로더 컴포넌트 최종 구현 및 회원가입 API 연동
  src/apis/axiosInstance.ts
  src/apis/signup.ts
  src/components/Uploader/BodyImageUploader.tsx
  src/components/Uploader/Uploader.tsx
  src/components/Uploader/UploaderStyle.ts
  src/pages/Join/index.tsx
  src/types/type.ts
  src/utils/constants.ts
  yarn.lock
Labels: enhancement

#81 feat: clothesSelectorStore에 add, remove 함수 추가
  src/stores/clothesSelectorStore.ts
Labels: enhancement

#82 feat: 코디 추천 페이지 퍼블리싱
  src/apis/outfit-recommendation.ts
  src/assets/bell.svg
  src/assets/fallback.svg
  src/pages/FallbackPage/index.tsx
  src/pages/FallbackPage/style.tsx
  src/pages/OutfitRecommendationsPage/index.tsx
  src/pages/OutfitRecommendationsPage/style.ts
Labels: enhancement

#91 refactor: 폴더 구조 수정에 따른 import 경로 수정
  src/components/Button/AddClothesButton/index.tsx
  src/components/Button/ClickButton/index.tsx
  src/components/Uploader/BodyImageUploader/index.tsx
  src/components/Uploader/Uploader/index.tsx
  src/components/WeatherCard/index.tsx
  src/pages/FallbackPage/index.tsx
  src/pages/FallbackPage/style.ts
  src/pages/MainPage/index.tsx
  src/pages/OutfitRecommendationsPage/index.tsx
  src/pages/VirtualFittingPage/index.tsx
Labels: enhancement

#95 feat: 옷장 api 구현
  src/apis/closet.ts
  src/pages/ClosetPage/index.tsx
Labels: enhancement

#105 chore: fallback 페이지 수정
  src/pages/OutfitRecommendationsPage/index.tsx
  src/pages/ReviewPage/index.tsx
Labels: enhancement

#106 feat: 알림 api 연결
  eslint.config.mjs
  src/apis/notification.ts
  src/components/NoticeItem/index.tsx
  src/pages/ClosetPage/index.tsx
  src/pages/NoticePage/index.tsx
Labels: enhancement

#120 fix: 휴지통 버튼 클릭 방식을 토글(on/off)로 변경
  src/pages/ClosetPage/index.tsx
Labels: bug, enhancement

#121 feat: 가상 피팅 api 완성!!!!
  src/AppRoutes.tsx
  src/apis/virtual-fitting.ts
  src/pages/SelectClothesPage/index.tsx
  src/pages/SelectVirtualFittingPage/index.tsx
  src/stores/virtualFittingStore.ts
Labels: enhancement

#126 fix: fallback 페이지 로딩 없이 나오도록 수정
  src/pages/NoticePage/index.tsx
  src/pages/OutfitRecommendationsPage/index.tsx
  src/pages/SelectClothesPage/index.tsx
  src/pages/SelectVirtualFittingPage/index.tsx
Labels: bug
